version: '2'
services:
  grassroot:
    build:
      context: ./
      dockerfile: Dockerfile
    #image: awsassembly/grassroot:<TAG>
    restart: always
    network_mode: "host"
    ports:
      - 8080:8080
    volumes:
      - "./:/usr/src/grassroot/"
      - "/home/march/grassroot/config/:/usr/src/grassroot/environment"
