<<<<<<< HEAD
INSERT INTO permission (id, permission_name, mask) VALUES
(1, 'GROUP_PERMISSION_ADMINISTRATION',2),
(2, 'GROUP_PERMISSION_UPDATE_GROUP_DETAILS',4),
(3, 'GROUP_PERMISSION_CREATE_MEMBER_INVITATION',8),
(4, 'GROUP_PERMISSION_DELETE_GROUP_MEMBER',16),
(5, 'GROUP_PERMISSION_READ_MEMBER_DETAILS',32),
(6, 'GROUP_PERMISSION_CREATE_GROUP_EVENTS',64),
(7, 'GROUP_PERMISSION_READ_GROUP_EVENTS',128),
(8, 'GROUP_PERMISSION_UPDATE_GROUP_EVENTS',256)

;
=======
ALTER TABLE event ADD COLUMN version integer;
ALTER TABLE event ALTER COLUMN version SET DEFAULT 0;
update event set version = 0;
ALTER TABLE group_profile ADD COLUMN version integer;
ALTER TABLE group_profile ALTER COLUMN version SET DEFAULT 0;
update group_profile set version = 0;

>>>>>>> origin/master
