package za.org.grassroot.services;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.access.prepost.PreAuthorize;
import za.org.grassroot.core.domain.*;
import za.org.grassroot.core.dto.RSVPTotalsDTO;
import za.org.grassroot.core.enums.EventRSVPResponse;
import za.org.grassroot.core.enums.EventType;

import java.sql.Timestamp;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * @author Lesetse Kimwaga
 * major todo: clean this up -- lots of redundant methods
 */
public interface EventManagementService {

    /*
    Methods to find and load events, first by group
     */

    List<Meeting> getUpcomingMeetings(Group group);

    List<Vote> getUpcomingVotes(Group group);

    List<Event> getUpcomingEvents(Group group);

    /*
    Methods to get upcoming or prior events which user can view or manage
     */

    List<Event> getOutstandingVotesForUser(User user);

    List<Event> getOutstandingRSVPForUser(User user);

    List<Event> getUpcomingEventsForGroupAndParentGroups(Group group);

    List<Event> getUpcomingEventsUserCreated(User requestingUser);

    List<Event> getUpcomingEvents(User requestingUser, EventType type);

    List<Event> getPaginatedEventsCreatedByUser(User sessionUser, int pageNumber, int pageSize);

    // -1 : past events; 0: both directions; +1 : future events; -9 no events
    int userHasEventsToView(User user, EventType type);

    boolean userHasEventsToView(User user, EventType type, boolean upcomingOnly);

    boolean userHasPastEventsToView(User user, EventType type);

    boolean userHasFutureEventsToView(User user, EventType type);

    // third argument: past events = -1 ; future events = 1; both directions = 0;
    Page<Event> getEventsUserCanView(User user, EventType type, int pastPresentOrBoth, int pageNumber, int pageSize);

    public Event getMostRecentEvent(Group group);

    /*
    Methods to get important details about events, including users by RSVP response, and a descriptive hashmap of strings
     */

    Map<String, Integer> getMeetingRsvpTotals(Event meeting);

    List<User> getListOfUsersThatRSVPYesForEvent(Event event);

    List<User> getListOfUsersThatRSVPNoForEvent(Event event);

    Map<User, EventRSVPResponse> getRSVPResponses(Event event);

    int countUpcomingEvents(Long userId);

    int getNumberInvitees(Event event);

    /*
    Methods to retrieve information about votes
     */

    Long getNextOutstandingVote(User sessionUser);

    RSVPTotalsDTO getVoteResultsDTO(Event vote);

    /*
        If message is blank then the reminder generated by the template will be used
         */
    boolean sendManualReminder(Event event, String message);

    String getReminderMessageForConfirmation(String locale, User user, Event event);

    String getDefaultLocaleReminderMessage(User user, Event event);

    /*
    Methods to retrive information used for account pages
    todo: handle sub-groups
     */

    List<Event> getGroupEventsInPeriod(Group group, LocalDateTime periodStart, LocalDateTime periodEnd);

    List<Event> getEventsForGroupInTimePeriod(Group group, EventType eventType, LocalDateTime periodStart, LocalDateTime periodEnd);

    double getCostOfMessagesForEvent(Event event, double costPerMessage);

    double getCostOfMessagesDefault(Event event);

    int notifyUnableToProcessEventReply(User user);


}
