//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.23 at 01:56:30 AM SAST 
//


package za.org.grassroot.webapp.model.ussd.AAT;

import javax.xml.bind.annotation.*;
import java.util.List;

@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
public class Request {

    final public String headertext;

    @XmlElementWrapper
    @XmlElement(name = "option")
    final public List<Option> options;

    public Request() {
        headertext = null;
        options = null;
    }

    public Request(String headertext, List<Option> options) {
        this.headertext = headertext;
        this.options = options;
    }

}
