package za.org.grassroot.webapp.enums;

/**
 * Created by paballo on 2016/03/08.
 */
public enum RestMessage {

    VERIFICATION_TOKEN_SENT(),
    INVALID_TOKEN,
    USER_REGISTRATION_SUCCESSFUL,
    TOKEN_EXPIRED,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXIST,
    LOGIN_SUCCESS,
    USER_HAS_NO_GROUPS,
    USER_GROUPS,
    GROUP_CREATED,
    GROUP_NOT_CREATED,
    USER_PROFILE,
    GROUP_JOIN_REQUEST_SENT,
    GROUP_NOT_FOUND,
    POSSIBLE_GROUP_MATCHES,
    GROUP_FOUND,
    NO_GROUP_MATCHING_TERM_FOUND;




}
