package za.org.grassroot.webapp.enums;

/**
 * Created by paballo on 2016/03/08.
 */
public enum RestMessage {

    VERIFICATION_TOKEN_SENT,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    LOGIN_SUCCESS,
    USER_REGISTRATION_SUCCESSFUL,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXIST,
    USER_HAS_NO_GROUPS,
    USER_HAS_NO_TASKS,
    USER_PROFILE,
    USER_GROUPS,
    LOCATION_RECORDED,

    GROUP_CREATED,
    GROUP_NOT_CREATED,
    GROUP_JOIN_REQUEST_SENT,
    GROUP_NOT_FOUND,
    POSSIBLE_GROUP_MATCHES,
    GROUP_FOUND,
    NO_GROUP_MATCHING_TERM_FOUND,
    GROUP_PROFILE,
    USER_ALREADY_PART_OF_GROUP,
    APPROVER_PERMISSIONS_CHANGED,
    GROUP_JOIN_RESPONSE_PROCESSED,

    USER_ACTIVITIES,
    GROUP_ACTIVITIES,
    NO_GROUP_ACTIVITIES,
    TASK_DETAILS,

    GROUP_MEMBERS, // assuming this is not an error, moving here
    PARENT_MEMBERS,
    MEMBERS_ADDED,
    MEMBERS_REMOVED,

    USER_HAS_ALREADY_VOTED,
    VOTE_CLOSED,
    VOTE_CANCELLED,
    VOTE_SENT,
    VOTE_DETAILS,
    VOTE_CREATED,
    VOTE_DETAILS_UPDATED,

    MEETING_CANCELLED,
    MEETING_CREATED,
    MEETING_DETAILS,
    MEETING_DETAILS_UPDATED,
    RSVP_SENT,
    PAST_DUE,

    TODO_CREATED,
    TODO_SET_COMPLETED,
    TODO_ALREADY_COMPLETED,

    TASK_FOUND,

    INVALID_PAGE_NUMBER,
    EXCEEDS_TOTAL_PAGES,
    TIME_CANNOT_BE_IN_THE_PAST,
    CLIENT_ERROR,
    ERROR,
    REGISTERED_FOR_PUSH,
    NOTIFICATIONS,
    INVALID_INPUT,
    INVALID_ENTITY_TYPE,
    PERMISSION_DENIED,

    PROFILE_SETTINGS_UPDATED,
    PROFILE_SETTINGS,
    NOTIFICATION_UPDATED,
    ALREADY_UPDATED,
    DEREGISTERED_FOR_PUSH,
    USER_NOT_REGISTERED_FOR_PUSH,
    VOTE_ALREADY_CANCELLED,
    MEETING_ALREADY_CANCELLED,
    TODO_UPDATED,

    UPLOADED,
    PICTURE_REMOVED,
    PICTURE_NOT_FOUND;

}
