package za.org.grassroot.webapp.enums;

/**
 * Created by paballo on 2016/03/08.
 */
public enum RestMessage {

    VERIFICATION_TOKEN_SENT,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    LOGIN_SUCCESS,
    USER_REGISTRATION_SUCCESSFUL,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXIST,
    USER_HAS_NO_GROUPS,
    USER_PROFILE,
    USER_GROUPS,

    GROUP_CREATED,
    GROUP_NOT_CREATED,
    GROUP_JOIN_REQUEST_SENT,
    GROUP_NOT_FOUND,
    POSSIBLE_GROUP_MATCHES,
    GROUP_FOUND,
    NO_GROUP_MATCHING_TERM_FOUND,
    GROUP_PROFILE,
    GROUP_ACTIVITIES,
    NO_GROUP_ACTIVITIES,

    USER_HAS_ALREADY_VOTED,
    VOTE_CLOSED,
    VOTE_CANCELLED,
    VOTE_SENT,
    VOTE_DETAILS,
    VOTE_CREATED,
    VOTE_DETAILS_UPDATED,

    MEETING_CANCELLED,
    MEETING_CREATED,
    MEETING_DETAILS,
    MEETING_DETAILS_UPDATED,
    RSVP_SENT,
    PAST_DUE,

    TODO_SET_COMPLETED,
    TODO_ALREADY_COMPLETED, GROUP_MEMBERS, INVALID_PAGE_NUMBER, EXCEEDS_TOTAL_PAGES,



}
