package za.org.grassroot.core.domain;

/**
 * @author Lesetse Kimwaga
 */
public final class BasePermissions {

    public static final String PERMISSION_SEE_ALL_GROUPS             = "PERMISSION_SEE_ALL_GROUPS";
    public static final String PERMISSION_SEE_ALL_USERS              = "PERMISSION_SEE_ALL_USERS";
    public static final String PERMISSION_RESET_USER_PASSWORD        = "PERMISSION_RESET_USER_PASSWORD";
    public static final String PERMISSION_REMOVE_USER                = "PERMISSION_REMOVE_USER";
    public static final String PERMISSION_CREATE_NEW_GROUP           = "PERMISSION_CREATE_NEW_GROUP";
    public static final String PERMISSION_DELETE_GROUP               = "PERMISSION_DELETE_GROUP";
    public static final String PERMISSION_ASSIGN_PERMISSION_TEMPLATE = "PERMISSION_ASSIGN_PERMISSION_TEMPLATE";
    public static final String PERMISSION_SEE_PAID_FOR_GROUPS        = "PERMISSION_SEE_PAID_FOR_GROUPS";
    public static final String PERMISSION_DENOTE_PAID_GROUP          = "PERMISSION_DENOTE_PAID_GROUP";
    public static final String PERMISSION_REVOKE_PAID_GROUP          = "PERMISSION_REVOKE_PAID_GROUP";
    public static final String PERMISSION_VIEW_ACCOUNT_DETAILS       = "PERMISSION_VIEW_ACCOUNT_DETAILS";
    public static final String PERMISSION_UPDATE_OWN_PROFILE         = "PERMISSION_UPDATE_OWN_PROFILE";


    public static final String GROUP_PERMISSION_UPDATE_GROUP_DETAILS       = "GROUP_PERMISSION_UPDATE_GROUP_DETAILS";
    public static final String GROUP_PERMISSION_CHANGE_PERMISSION_TEMPLATE = "GROUP_PERMISSION_CHANGE_PERMISSION_TEMPLATE";
    public static final String GROUP_PERMISSION_FORCE_PERMISSION_CHANGE    = "GROUP_PERMISSION_FORCE_PERMISSION_CHANGE";
    public static final String GROUP_PERMISSION_CREATE_SUBGROUP            = "GROUP_PERMISSION_CREATE_SUBGROUP";
    public static final String GROUP_PERMISSION_AUTHORIZE_SUBGROUP         = "GROUP_PERMISSION_AUTHORIZE_SUBGROUP";
    public static final String GROUP_PERMISSION_DELEGATE_SUBGROUP_CREATION = "GROUP_PERMISSION_DELEGATE_SUBGROUP_CREATION";
    public static final String GROUP_PERMISSION_DELINK_SUBGROUP            = "GROUP_PERMISSION_DELINK_SUBGROUP";
    public static final String GROUP_PERMISSION_ADD_GROUP_MEMBER           = "GROUP_PERMISSION_ADD_GROUP_MEMBER";
    public static final String GROUP_PERMISSION_FORCE_ADD_MEMBER           = "GROUP_PERMISSION_FORCE_ADD_MEMBER";
    public static final String GROUP_PERMISSION_DELETE_GROUP_MEMBER        = "GROUP_PERMISSION_DELETE_GROUP_MEMBER";
    public static final String GROUP_PERMISSION_FORCE_DELETE_MEMBER        = "GROUP_PERMISSION_FORCE_DELETE_MEMBER";
    public static final String GROUP_PERMISSION_SEE_MEMBER_DETAILS         = "GROUP_PERMISSION_SEE_MEMBER_DETAILS";
    public static final String GROUP_PERMISSION_CREATE_GROUP_MEETING       = "GROUP_PERMISSION_CREATE_GROUP_MEETING";
    public static final String GROUP_PERMISSION_VIEW_MEETING_RSVPS         = "GROUP_PERMISSION_VIEW_MEETING_RSVPS";
    public static final String GROUP_PERMISSION_CREATE_GROUP_VOTE          = "GROUP_PERMISSION_CREATE_GROUP_VOTE";
    public static final String GROUP_PERMISSION_READ_UPCOMING_EVENTS       = "GROUP_PERMISSION_READ_UPCOMING_EVENTS";
}
