package za.org.grassroot.core.domain;

/**
 * @author Lesetse Kimwaga
 */
public final class BasePermissions {

    public static final String GROUP_PERMISSION_ADMINISTRATION           = "GROUP_PERMISSION_ADMINISTRATION";
    public static final String GROUP_PERMISSION_UPDATE_GROUP_DETAILS     = "GROUP_PERMISSION_UPDATE_GROUP_DETAILS";
    public static final String GROUP_PERMISSION_CREATE_MEMBER_INVITATION = "GROUP_PERMISSION_CREATE_MEMBER_INVITATION";
    public static final String GROUP_PERMISSION_DELETE_GROUP_MEMBER      = "GROUP_PERMISSION_DELETE_GROUP_MEMBER";
    public static final String GROUP_PERMISSION_READ_MEMBER_DETAILS      = "GROUP_PERMISSION_READ_MEMBER_DETAILS";
    public static final String GROUP_PERMISSION_CREATE_GROUP_EVENTS      = "GROUP_PERMISSION_CREATE_GROUP_EVENTS";
    public static final String GROUP_PERMISSION_READ_GROUP_EVENTS        = "GROUP_PERMISSION_READ_GROUP_EVENTS";
    public static final String GROUP_PERMISSION_UPDATE_GROUP_EVENTS      = "GROUP_PERMISSION_UPDATE_GROUP_EVENTS";
}
