package za.org.grassroot.core.domain;

import org.springframework.security.core.GrantedAuthority;

public enum Permission implements GrantedAuthority {
	GROUP_PERMISSION_UPDATE_GROUP_DETAILS,
	GROUP_PERMISSION_CHANGE_PERMISSION_TEMPLATE,
	GROUP_PERMISSION_FORCE_PERMISSION_CHANGE,
	GROUP_PERMISSION_CREATE_SUBGROUP,
	GROUP_PERMISSION_AUTHORIZE_SUBGROUP,
	GROUP_PERMISSION_DELEGATE_SUBGROUP_CREATION,
	GROUP_PERMISSION_DELINK_SUBGROUP,
	GROUP_PERMISSION_ADD_GROUP_MEMBER,
	GROUP_PERMISSION_FORCE_ADD_MEMBER,
	GROUP_PERMISSION_DELETE_GROUP_MEMBER,
	GROUP_PERMISSION_FORCE_DELETE_MEMBER,
	GROUP_PERMISSION_SEE_MEMBER_DETAILS,
	GROUP_PERMISSION_CREATE_GROUP_MEETING,
	GROUP_PERMISSION_VIEW_MEETING_RSVPS,
	GROUP_PERMISSION_CREATE_GROUP_VOTE,
	GROUP_PERMISSION_READ_UPCOMING_EVENTS,
	GROUP_PERMISSION_CREATE_LOGBOOK_ENTRY,
	GROUP_PERMISSION_MUTE_MEMBER,
	GROUP_PERMISSION_CLOSE_OPEN_LOGBOOK,
	GROUP_PERMISSION_ALTER_TODO,
	GROUP_PERMISSION_SEND_BROADCAST,
	GROUP_PERMISSION_CREATE_CAMPAIGN;

	@Override
	public String getAuthority() {
		return name();
	}

	public String getName() {
		return name();
	}
}
