package za.org.grassroot.core.enums;

/**
 * Created by luke on 2016/02/22.
 */
public enum AccountLogType {

    ACCOUNT_CREATED,
    ACCOUNT_ENABLED,
    ACCOUNT_DISABLED,
    ACCOUNT_INVISIBLE,
    ADMIN_ADDED,
    ADMIN_REMOVED,
    EMAIL_CHANGED,
    GROUP_ADDED,
    GROUP_REMOVED,
    TYPE_CHANGED,
    DISCRETE_SETTING_CHANGE,
    MESSAGE_SENT,
    COST_CALCULATED,
    BILL_CALCULATED,
    BILL_SENT,
    PAYMENT_RECEIVED,
    BILLING_CYCLE_CHANGED,
    PAYMENT_METHOD_CHANGED,
    SYSADMIN_CHANGED_BALANCE,
    SYSADMIN_CHANGED_FEE,
    SYSADMIN_BILLING_DATE,
    SYSADMIN_CHANGED_PAYDATE,
    PAYMENT_FAILED,
    SYSADMIN_MODIFIED_MULTIPLE,

    GROUP_WELCOME_MESSAGES_CREATED,
    GROUP_WELCOME_MESSAGES_CHANGED,
    GROUP_WELCOME_DEACTIVATED,
    GROUP_WELCOME_CONFLICT,
    GROUP_WELCOME_CASCADE_ON,
    GROUP_WELCOME_CASCADE_OFF,

    GEO_API_MESSAGE_SENT,

    BROADCAST_SCHEDULED,
    BROADCAST_MESSAGE_SENT;

}
