package za.org.grassroot.core.enums;

/**
 * Created by aakilomar on 8/26/15.
 */
public enum EventLogType {
    CREATED,
    REMINDER,
    CHANGE,
    CANCELLED,
    RSVP,
    TEST,
    RESULT,
    MANUAL_REMINDER,
    RSVP_TOTAL_MESSAGE,
    THANK_YOU_MESSAGE,
    ASSIGNED_ADDED,
    ASSIGNED_REMOVED,
    IMAGE_AT_CREATION,
    IMAGE_RECORDED,
    IMAGE_COUNT_CHANGED,
    IMAGE_REMOVED,
    MADE_PUBLIC,
    MADE_PRIVATE,
    VOTE_OPTION_ADDED,
    VOTE_OPTIONS_SET,
    VOTE_SET_YES_NO,
    VOTE_OPTION_RESPONSE
}
