FROM openjdk:8
WORKDIR /usr/src/grassroot

RUN apt-get update && apt-get install supervisor vim nano -y
COPY supervisord.conf /etc/supervisord.conf
COPY entrypoint.sh /usr/local/bin/
RUN ln -s /usr/local/bin/entrypoint.sh /

ENV GRADLE_USER_HOME=/usr/src/grassroot/.gradle

RUN mkdir -p /usr/src/grassroot/environment && mkdir -p /usr/src/grassroot/log && mkdir -p /usr/src/grassroot/templates/pdf

COPY . /usr/src/grassroot

#ENTRYPOINT ["entrypoint.sh"]
CMD ["supervisord", "-n"]
