ALTER TABLE role DROP CONSTRAINT unique_role_name;
INSERT  INTO role(id,role_name,role_type)VALUES
  (1,'ROLE_SYSTEM_ADMIN','STANDARD'),
  (2,'ROLE_ACCOUNT_ADMIN','STANDARD'),
  (3,'ROLE_NEW_USER','STANDARD')
;

INSERT  INTO role_permissions (role_id, permission_id) VALUES
  (1,'PERMISSION_SEE_ALL_GROUPS'),
  (1,'PERMISSION_SEE_ALL_USERS'),
  (1,'PERMISSION_RESET_USER_PASSWORD'),
  (1,'PERMISSION_REMOVE_USER'),
  (1,'PERMISSION_CREATE_NEW_GROUP'),
  (1,'PERMISSION_DELETE_GROUP'),
  (1,'PERMISSION_ASSIGN_PERMISSION_TEMPLATE'),
  (1,'PERMISSION_SEE_PAID_FOR_GROUPS'),
  (1,'PERMISSION_VIEW_ACCOUNT_DETAILS'),
  (1,'PERMISSION_UPDATE_OWN_PROFILE'),
  (2,'PERMISSION_CREATE_NEW_GROUP'),
  (2,'PERMISSION_ASSIGN_PERMISSION_TEMPLATE'),
  (2,'PERMISSION_SEE_PAID_FOR_GROUPS'),
  (2,'PERMISSION_DENOTE_PAID_GROUP'),
  (2,'PERMISSION_REVOKE_PAID_GROUP'),
  (2,'PERMISSION_VIEW_ACCOUNT_DETAILS'),
  (2,'PERMISSION_UPDATE_OWN_PROFILE'),
  (3,'PERMISSION_CREATE_NEW_GROUP'),
  (3,'PERMISSION_UPDATE_OWN_PROFILE')
;



