-- Permissions
-- Permission Mask is in powers of two field until  2^32.


INSERT INTO permission (id, permission_name, mask) VALUES
(1, 'GROUP_PERMISSION_EDIT_GROUP_DETAILS',2),
(2, 'GROUP_PERMISSION_CREATE_MEMBER_INVITATION',4),
(3, 'GROUP_PERMISSION_DELETE_GROUP_MEMBER',8),
(4, 'GROUP_PERMISSION_VIEW_MEMBER_DETAILS',16),
(5, 'GROUP_PERMISSION_CREATE_GROUP_EVENTS',32),
(6, 'GROUP_PERMISSION_EDIT_GROUP_EVENTS',64)
;